### ISSUE TITLE
在本机执行脚本后提示num未定义，以及action部署报错

### ISSUE THREAD

**Issue by Wutpeach** [findmover/wxread#12]
Traceback (most recent call last):
  File "C:\Users\winlo\Desktop\wxread-main\main.py", line 75, in <module>
    print(f"-------------------第{num}次，共阅读{num * 0.5}分钟-------------------")
                                  ^^^
NameError: name 'num' is not defined. Did you mean: 'sum'?

在main里num = 1 后能正常运行。
------
action部署时提示：
File "/home/runner/work/wxread/wxread/main.py", line 26, in 
headers = json.loads(env_headers) if env_headers else local_headers
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by findmover** [comment]
已解决，单引号问题；去掉抓包得到的headers=，cookies=，填入后面的字典格式；
